version: "3"
services:
  mysql:
    container_name: mysql
    platform: linux/amd64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
